package us.percept.pile.view;

import us.percept.pile.model.Paper;

import javax.swing.*;
import java.awt.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 * Author: spartango
 * Date: 8/5/13
 * Time: 2:56 AM.
 */
public class PaperView extends JPanel implements ListCellRenderer {
    private JLabel    titleField;
    private JLabel    authorsField;
    private JTextArea summaryArea;
    private JLabel    dateField;
    private JLabel    pdfLabel;

    @Override public Component getListCellRendererComponent(JList list,
                                                            Object value,
                                                            int index,
                                                            boolean isSelected,
                                                            boolean cellHasFocus) {
        // Value should be a paper
        if (value instanceof Paper) {
            Paper paper = (Paper) value;
            titleField.setText(paper.getTitle());

            StringBuilder authorString = new StringBuilder();
            java.util.List<String> authors = paper.getAuthors();

            // Get the last author and guard against empty authors
            String lastAuthor = authors.size() > 0 ? authors.get(authors.size() - 1) : authors.get(0);
            for (String author : authors) {
                authorString.append(author);
                if(author != lastAuthor) {
                    authorString.append(", ");
                }
            }
            authorsField.setText(authorString.toString());
            summaryArea.setText(paper.getSummary());

            DateFormat df = new SimpleDateFormat("MMM yyy");
            String date = df.format(paper.getDate());
            dateField.setText(date);

            // TODO set the PDF label and it's linky-ness
        }
        // Populate the fields from the paper
        return this;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        this.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        this.setBackground(new Color(-1));
        titleField = new JLabel();
        titleField.setFont(new Font(titleField.getFont().getName(), Font.BOLD, 16));
        titleField.setText("Title");
        titleField.setVerticalAlignment(0);
        this.add(titleField,
                 new com.intellij.uiDesigner.core.GridConstraints(0,
                                                                  0,
                                                                  1,
                                                                  1,
                                                                  com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                  com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                  null,
                                                                  new Dimension(430, 20),
                                                                  null,
                                                                  1,
                                                                  false));
        authorsField = new JLabel();
        authorsField.setBackground(new Color(-1));
        authorsField.setText("Authors");
        this.add(authorsField,
                 new com.intellij.uiDesigner.core.GridConstraints(1,
                                                                  0,
                                                                  1,
                                                                  1,
                                                                  com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                  com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                  1,
                                                                  null,
                                                                  new Dimension(430, 16),
                                                                  null,
                                                                  1,
                                                                  false));
        summaryArea = new JTextArea();
        summaryArea.setEditable(false);
        summaryArea.setLineWrap(true);
        summaryArea.setText("This is a summary of the article presented here.");
        dateField = new JLabel();
        dateField.setEnabled(false);
        dateField.setFont(new Font(dateField.getFont().getName(), Font.ITALIC, dateField.getFont().getSize()));
        dateField.setText("Jan 2013");
        this.add(dateField,
                 new com.intellij.uiDesigner.core.GridConstraints(0,
                                                                  1,
                                                                  1,
                                                                  1,
                                                                  com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST,
                                                                  com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                  1,
                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                  null,
                                                                  null,
                                                                  null,
                                                                  0,
                                                                  false));
        pdfLabel = new JLabel();
        pdfLabel.setForeground(UIManager.getColor("controlHighlight"));
        pdfLabel.setText("PDF");
        this.add(pdfLabel,
                 new com.intellij.uiDesigner.core.GridConstraints(1,
                                                                  1,
                                                                  1,
                                                                  1,
                                                                  com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST,
                                                                  com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                  com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                  null,
                                                                  null,
                                                                  null,
                                                                  0,
                                                                  false));
        final JSeparator separator1 = new JSeparator();
        this.add(separator1,
                   new com.intellij.uiDesigner.core.GridConstraints(2,
                                                                    0,
                                                                    1,
                                                                    2,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    0,
                                                                    false));
        summaryArea = new JTextArea();
        this.add(summaryArea,
                   new com.intellij.uiDesigner.core.GridConstraints(3,
                                                                    0,
                                                                    1,
                                                                    2,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    null,
                                                                    new Dimension(150, 50),
                                                                    null,
                                                                    1,
                                                                    false));
        final JSeparator separator2 = new JSeparator();
        this.add(separator2,
                   new com.intellij.uiDesigner.core.GridConstraints(4,
                                                                    0,
                                                                    1,
                                                                    2,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    0,
                                                                    false));
    }
}
