package us.percept.pile.view;

import javax.swing.*;
import java.awt.*;

/**
 * Author: spartango
 * Date: 8/4/13
 * Time: 10:04 PM.
 */
public class PileView extends JPanel {
    private JTextField  searchField;
    private JScrollPane listScrollPane;
    private JList       paperList;

    private void createUIComponents() {
        searchField = new JTextField();
        listScrollPane = new JScrollPane();
        paperList = new JList();
        paperList.setCellRenderer(new PaperView());
    }

    public void setListData(Object[] listData) {
        paperList.setListData(listData);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        this.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        searchField = new JTextField();
        this.add(searchField,
                   new com.intellij.uiDesigner.core.GridConstraints(0,
                                                                    0,
                                                                    1,
                                                                    1,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    null,
                                                                    new Dimension(150, -1),
                                                                    null,
                                                                    0,
                                                                    false));
        listScrollPane = new JScrollPane();
        this.add(listScrollPane,
                   new com.intellij.uiDesigner.core.GridConstraints(1,
                                                                    0,
                                                                    1,
                                                                    1,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                    | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                    | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    0,
                                                                    false));
        listScrollPane.setViewportView(paperList);
    }
}
