import javax.swing.*;
import java.awt.*;

/**
 * Author: spartango
 * Date: 8/5/13
 * Time: 3:50 AM.
 */
public class N {
    private JTextArea summaryArea;
    private JLabel    titleField;
    private JLabel    dateField;
    private JLabel    authorsField;
    private JLabel    pdfLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        titleField = new JLabel();
        titleField.setText("Label");
        panel1.add(titleField,
                   new com.intellij.uiDesigner.core.GridConstraints(0,
                                                                    0,
                                                                    1,
                                                                    1,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    0,
                                                                    false));
        dateField = new JLabel();
        dateField.setText("Label");
        panel1.add(dateField,
                   new com.intellij.uiDesigner.core.GridConstraints(0,
                                                                    1,
                                                                    1,
                                                                    1,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    0,
                                                                    false));
        authorsField = new JLabel();
        authorsField.setText("Label");
        panel1.add(authorsField,
                   new com.intellij.uiDesigner.core.GridConstraints(1,
                                                                    0,
                                                                    1,
                                                                    1,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    0,
                                                                    false));
        pdfLabel = new JLabel();
        pdfLabel.setText("Label");
        panel1.add(pdfLabel,
                   new com.intellij.uiDesigner.core.GridConstraints(1,
                                                                    1,
                                                                    1,
                                                                    1,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    0,
                                                                    false));
        final JSeparator separator1 = new JSeparator();
        panel1.add(separator1,
                   new com.intellij.uiDesigner.core.GridConstraints(2,
                                                                    0,
                                                                    1,
                                                                    2,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    0,
                                                                    false));
        summaryArea = new JTextArea();
        panel1.add(summaryArea,
                   new com.intellij.uiDesigner.core.GridConstraints(3,
                                                                    0,
                                                                    1,
                                                                    2,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    null,
                                                                    new Dimension(150, 50),
                                                                    null,
                                                                    1,
                                                                    false));
        final JSeparator separator2 = new JSeparator();
        panel1.add(separator2,
                   new com.intellij.uiDesigner.core.GridConstraints(4,
                                                                    0,
                                                                    1,
                                                                    2,
                                                                    com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH,
                                                                    com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                    com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    0,
                                                                    false));
    }
}
